### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by kvmanohar22** [dishank-b/Deep-Blur#2]
- [ ] Incorporating UNet for generator
- [ ] Multivariate Latent Vector (maybe `2D` ?) for noise generation
- [ ] Incorporating `L1` term for encoder decoder part
